name: CI
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '~/.cache'
          key: ${{ runner.os }}-cache-${{ hashFiles('**/yarn.lock') }}
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      # - run: yarn format:check
      # - run: yarn lint
      # - run: yarn jest
      - run: yarn build
      # - run: yarn cypress
